apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_HOST: bXlzcWwtMC5teXNxbC1oLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=
