apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
stringData:
  MYSQL_ROOT_PASSWORD: "TXlSb290U3Ryb25nUGFzc3dvcmQ=" #MyRootStrongPassword
  MYSQL_USER: "bXlzcWxrOHN1c2Vy" #mysqlk8suser
  MYSQL_PASSWORD: "TXlTdHJvbmdQYXNzd29yZA==" #MyStrongPassword
