apiVersion: v1
kind: Service
metadata:
  name: mysql-node
  namespace: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
      nodePort: 30007
