apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  NAME: "dG9kb2FwcF9kYgo="
  USER: "dG9kb2FwcF91c2VyCg=="
  PASSWORD: "MTIzNA=="
  HOST: "bXlzZ2wrbXlzcWxjb25uZWN0b3I6Ly90b2RvYXBwX3VzZXI6MTIzNEBteXNxbC0wLnRvZG9hcHAtbXlzcWwubXlzcWwuc3ZjLmNsdXN0ZXIubG9jYWwvdG9kb2FwcF9kYgo="

