apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  NAME: bXlkYXRhYmFzZQ==
  USER: bXl1c2Vy
  PASSWORD: bXlwYXNzd29yZA==
  HOST: bXlzcWwtMC5teXNxbC1oLm15c3FsLnN2Yy5jbHVzdGVyLmxvY2FsCg==
