apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "UEBzc3cwcmQ=" #Base64 "P@ssw0rd"
  MYSQL_DATABASE: "YXBwX2Ri" #Base64 "app_db"
  MYSQL_USER: "bXlzcWx1c2Vy" #Base64 "mysqluser"
  MYSQL_PASSWORD: "UEBzc3cwcmQ=" #Base64 "P@ssw0rd"
  MYSQL_HOST: "bG9jYWxob3N0" #Base64 "localhost"
