apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2
  MYSQL_USER: YXBwX3VzZXI=
  MYSQL_PASSWORD: MTIzNDU2
  MYSQL_HOST: bG9jYWxob3N0
