apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNA==  #1234
  MYSQL_USER: bXlzcWx1c2Vy       #mysqluser
  MYSQL_PASSWORD: dXNlcnB3       #userpw
