apiVersion: v1
kind: Secret
metadata:
 name: mysql-secrets
 namespace: mysql
type: Opaque
data: 
  MYSQL_ROOT_PASSWORD: "MTIzNAo="
  MYSQL_USER: "VXNlcg=="
  MYSQL_PASSWORD: "MTIzNAo="
  MYSQL_HOST: bXlzcWwtMC5teXNxbAo=
  