apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: mysql
data:
  init.sql: |
    CREATE USER 'mysqluser'@'%' IDENTIFIED BY 'P@ssw0rd';
    GRANT ALL PRIVILEGES ON app_db.* TO 'mysqluser'@'%';
    USE app_db;
