apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9vdFBhc3N3b3Jk # RootPassword  encoded in base64
  MYSQL_USER: dXNlcjE=                  # user1         encoded in base64
  MYSQL_PASSWORD: dXNlcjFQYXNz          # user1Pass     encoded in base64
