apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql-config
  namespace: mysql 
data: 
  init.sql: |   
    CREATE USER 'mysqluser'@'%' IDENTIFIED BY 'mysqlpw';
    GRANT ALL PRIVILEGES ON app_db.* TO 'mysqluser'@'%';
    USE app_db;
