apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "bXlyb290cHc=" #myrootpw
  MYSQL_USER: "bXlzcWx1c2Vy" #mysqluser
  MYSQL_PASSWORD: "bXlzcWxwdw==" #mysqlpw
